## Run_analysis.R creates two sets of tidy data using publically availabe data
## collected from the accelerometers from the Samsung Galaxy S smartphone
## The first set is generated by extracting features that contain mean and std 
## from train and test data, and merging these data together
## The second set is generated by averaging columns for each feature for a given
## activity defined in activity_list.txt

## Start with obtaining the data:
## Create data directory if does not exist, download zipped data, extract zip data
## read extracted data
## Lines 13-19 are commendted, dowloading ~ 65MB file may take awhile so skip this step
## if you already have data

#if(!file.exists("./data")){dir.create("./data")}
#fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
#download.file(fileUrl, destfile = "./data/Dataset.zip", method="auto", mode="wb" )
#dateDownloaded <- date()
#print(dateDownloaded)
#zipfile <- "./data/Dataset.zip"
#unzip(zipfile)

# define directory where the tidy data sets will be saved
directory <- "./UCI HAR Dataset" 

# need to create empty data frame for later use
dfTmp <- data.frame()

# read from top level directory
activityLabels <- read.table("UCI HAR Dataset/activity_labels.txt")
features <- read.table("UCI HAR Dataset/features.txt")

## Read from train direcotry
subjectTrain <- read.table("UCI HAR Dataset/train/subject_train.txt",colClasses = "numeric" )
Xtrain <- read.table("UCI HAR Dataset/train/X_train.txt", colClasses = "numeric")
ytrain <- read.table("UCI HAR Dataset/train/y_train.txt", colClasses = "numeric")

## Read from test directory
subjectTest <- read.table("UCI HAR Dataset/test/subject_test.txt", colClasses = "numeric")
Xtest <- read.table("UCI HAR Dataset/test/X_test.txt", colClasses = "numeric")  
ytest <- read.table("UCI HAR Dataset/test/y_test.txt", colClasses = "numeric")

## get indices for std and mean from features using grep (79 variables of interest)
stdIdx <- grep("std", features$V2)
meanIdx <- grep("mean", features$V2)
tmp <- c(stdIdx,meanIdx)
# stmp contains sorted indices corresponding to 
stmp <- sort(tmp)

## subset test and train with stmp 
## to extract data frames with colums of interest
## e.g., XtrainSub has 7352 observables of 79 variables
XtestSub <- Xtest[, stmp]
XtrainSub <- Xtrain[,stmp]

## get names of features of interest
feaSub <- as.character(features$V2[stmp])

## Add 2 columns to XtestSub and XtrainSub: 
## the first column is subject from subjectXXX
## the second column is activity from yXXX
XtestNew <- cbind(ytest,subjectTest, XtestSub)
XtrainNew <- cbind(ytrain,subjectTrain,XtrainSub)

## create lables for columns
feaSubNew <- c("activity","subject", feaSub)

## label columns in XtestNew and XtrainNew using feaSubNew
colnames(XtestNew) <- feaSubNew
colnames(XtrainNew) <- feaSubNew
## check column names with names(XtestNew) and names(XtrainNew)

## now we have 2 data frames ready to be merged
mergeData <- rbind(XtestNew,XtrainNew)

## sort data by subject and activity
orderMdata <- mergeData[order(mergeData$activity,mergeData$subject),]

## write tidy data into file
write.table(orderMdata, file = "UCI HAR Dataset/tidyData1.txt", row.names = FALSE)
write.csv(orderMdata, file = "UCI HAR Dataset/tidyData1.csv", row.names = FALSE)

## split data into separate files by the activity
splitList <- split(orderMdata, orderMdata[,1])

##  individual activities
ndx <- seq(length(activityLabels[,1])) # activity index sequence
sndx <- seq(max(subjectTrain)) # subject index
d
fRbind <- data.frame()

## loop over activities and split data frame by subjects
## then, loop over subjects and avarage columns
## add avarages into data frame dfRbind

for (i in ndx) {
        dfTmp <- as.data.frame(splitList[i])
        #tmpFile <- sprintf("%s/activity_%0i.txt", directory, i)
        #write.table(dfTmp, file = tmpFile , row.names = FALSE)
        
        lstTmp <- split(dfTmp, dfTmp[,2])
        
                for (j in sndx) {
                        tmp01 <- colMeans(as.data.frame(lstTmp[j]))
                        dfRbind <- rbind(dfRbind,tmp01)
                }
        
}

## replace colum names and write tidy data set into TidyAverages.txt file

tmpFile <- sprintf("%s/TidyAverages.txt", directory)
colnames(dfRbind) <- feaSubNew
write.table(dfRbind, file = tmpFile , row.names = FALSE, )


